/**
 * The open-source notices the app ships with (TD-28), generated by scripts/licenses.js from the
 * installed packages and the bundled assets. Licence texts are shared between entries.
 */
import data from './licenses.json';

export type Notice = {
  name: string;
  license: string;
  copyright: string[];
  /** Index into `texts`; null when no licence text could be found. */
  text: number | null;
};

export const assets: Notice[] = data.assets;
export const packages: Notice[] = data.packages;
export const texts: string[] = data.texts;
