/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description The caller's jobs, newest first (uses the jobs(user_id, created_at) index).
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Step 1: create a job and get a presigned URL to upload the audio to.
         */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Job
         * @description Step 3: check the upload and the quota, then queue the job. Safe to repeat.
         *
         *     Only size, type and quota are checked here (one HEAD request). Duration and format need
         *     the audio decoded, so the normalize stage checks them and fails the job if they're wrong.
         */
        post: operations["submit_job_jobs__job_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Step 5: poll a job's status; once it has succeeded, `outputs` has download links.
         */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Delete a job, its scores and its files. It still counts towards this month's quota.
         *
         *     A running job can be deleted too: its worker drops the job's remaining stages and removes
         *     any files it writes after this (worker.handler).
         */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/push-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Register Push Token
         * @description Notify this device about the caller's jobs. Safe to repeat; a device that was another
         *     user's moves to the caller (it signed in as someone else).
         */
        put: operations["register_push_token_me_push_tokens_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/push-tokens/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Push Token
         * @description Stop notifying this device (sign-out, or notifications turned off). Only the caller's own
         *     tokens can be removed; anything else is quietly ignored, so this can't probe tokens.
         */
        delete: operations["remove_push_token_me_push_tokens__token__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is up.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: Postgres and Redis answer. Object storage isn't checked: it's a remote service
         *     whose outage shouldn't take every API instance out of the load balancer.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the bearer token belongs to, and how much of this month's quota is used.
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateJobRequest */
        CreateJobRequest: {
            instrument: components["schemas"]["Instrument"];
            /** @default standard */
            tuning?: components["schemas"]["Tuning"];
            /**
             * Capo
             * @default 0
             */
            capo?: number;
            /**
             * Content Type
             * @description One of: audio/aac, audio/flac, audio/mp4, audio/mpeg, audio/ogg, audio/wav, audio/wave, audio/x-m4a, audio/x-wav
             */
            content_type: string;
            /**
             * Size Bytes
             * @description Size of the file the client will upload
             */
            size_bytes: number;
            /**
             * Name
             * @description Optional title
             */
            name?: string | null;
        };
        /** CreateJobResponse */
        CreateJobResponse: {
            job: components["schemas"]["JobOut"];
            upload: components["schemas"]["PresignedRequestOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Instrument
         * @enum {string}
         */
        Instrument: "guitar" | "piano";
        /** JobError */
        JobError: {
            /** Code */
            code: string;
            /** Message */
            message: string | null;
        };
        /** JobList */
        JobList: {
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * JobOptions
         * @description What the client can choose. Stored as the job's config and read by the worker as the
         *     pipeline's `PipelineConfig` (a test keeps the two compatible). The API doesn't import the
         *     pipeline: it would pull the ML libraries into the API.
         */
        JobOptions: {
            instrument: components["schemas"]["Instrument"];
            /** @default standard */
            tuning: components["schemas"]["Tuning"];
            /**
             * Capo
             * @default 0
             */
            capo: number;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            status: components["schemas"]["JobStatus"];
            options: components["schemas"]["JobOptions"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Pipeline Version */
            pipeline_version: string | null;
            error: components["schemas"]["JobError"] | null;
            /** Stages */
            stages: components["schemas"]["StageOut"][];
            outputs: components["schemas"]["JobOutputs"] | null;
        };
        /**
         * JobOutputs
         * @description Presigned downloads of the job's latest score version.
         */
        JobOutputs: {
            /** Version */
            version: number;
            musicxml: components["schemas"]["PresignedRequestOut"];
            tab_musicxml: components["schemas"]["PresignedRequestOut"] | null;
            midi: components["schemas"]["PresignedRequestOut"] | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending_upload" | "queued" | "running" | "succeeded" | "failed";
        /** JobSummary */
        JobSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            status: components["schemas"]["JobStatus"];
            instrument: components["schemas"]["Instrument"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MeOut */
        MeOut: {
            /** User Id */
            user_id: string;
            /** Jobs This Month */
            jobs_this_month: number;
            /** Jobs Per Month */
            jobs_per_month: number;
        };
        /** PresignedRequestOut */
        PresignedRequestOut: {
            /** Method */
            method: string;
            /** Url */
            url: string;
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /** Expires In S */
            expires_in_s: number;
        };
        /** PushTokenIn */
        PushTokenIn: {
            /** Token */
            token: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "ios" | "android";
        };
        /** StageOut */
        StageOut: {
            /** Stage */
            stage: string;
            status: components["schemas"]["StageStatus"];
            /** Attempts */
            attempts: number;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "queued" | "running" | "succeeded" | "skipped" | "failed" | "cached";
        /**
         * Tuning
         * @enum {string}
         */
        Tuning: "standard" | "drop_d";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_jobs__job_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_push_token_me_push_tokens_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_push_token_me_push_tokens__token__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
}
